### ISSUE TITLE
SISEC 2018

### ISSUE THREAD

**Issue by faroit** [soobin3230/wavenet#1]
Hi, 

this project looks nice. Is there an accompanying paper for it as well?
In any case, I would like to encourage you to participate in the SiSEC 2018 MUS task: https://github.com/sigsep/sigsep-mus-2018

**Comment by soobinseo** [comment]
Hi, thank you for interest.
As far as I know, there is no accompanying paper for this project.
I will consider your recommendation. Thank you.

**Comment by faroit** [comment]
You don't need a paper to contribute to sisec. So we would be really happy if you contribute. If you need any help, just let me know.
